### ISSUE TITLE
Share global SCSS variable across React SCSS Styles

### ISSUE THREAD

**Issue by webberwang** [reactql/cli#102]
I could import the variable file to each component that I want to use, but that would get a bit verbose. If there's a way to declare by variables in one file, for me to reference that when building my React components that would be great.

Thanks

**Comment by webberwang** [comment]
So while SCSS variables are scoped to the file, I noticed variables set with css syntax can get shared.

main.global.scss
```
:root {
  --color-primary: blue;
}
```

another-file.scss
```
body {
  background-color: var(--color-primary);
}
```

I also noticed that imported styles in the `src/app.js` get loaded last, after any component styles. So if order for the CSS variables to be picked up by other components, we need to declare them first. I found the root component file to be a good place to set those declarations, as they are loaded first. This is inside `src/components/main/index.js`

**Comment by webberwang** [comment]
I've concluded that importing the variable SCSS file on a file basis is better practice, and is more inline with the concept of dependency injection and scope.

**Comment by jonoirwinrsa** [comment]
@webberwang whats the issue with importing your variable file in each component stylesheet?
Should be a one-liner and all your vars will be available..

Personally I have variable file for fonts, colors and metrics.. Then import them all into an index file and import that index file into each component stylesheet `@import '../../theme/index';`

**Comment by webberwang** [comment]
I'm just worried about performance hit for hot reload

**Comment by jonoirwinrsa** [comment]
This shouldn't make a difference to that

**Comment by maximus-lynn** [comment]
Jonoirwinrsa - The issue is you have to write one line for every component rather writing it in one place working across all components. It is wasted dev time and opens developers to making mistakes if they forget.

**Comment by jonoirwinrsa** [comment]
@maximus-lynn personally I can't really see it being much of an issue - my code won't even compile if I leave the theme import out.

Its not like people are complaining about having to import React into their components - but I guess each to their own ¯\_(ツ)_/¯

If you come up with another solution let me know :)
