### ISSUE TITLE
      "message": "Expected [object Object] to be a GraphQL schema."

### ISSUE THREAD

**Issue by msman** [reactql/cli#109]
hi,

I followed the video here [https://www.youtube.com/watch?v=DNPVqK_woRQ](url) it is really great. thank you for that.

 I only get the following error in the screenshot below:

![untitled22](https://user-images.githubusercontent.com/12930906/37554863-d81773e4-29ef-11e8-8e7d-ca6518a11ad3.png)
 
please help!

**Comment by leebenson** [comment]
This is best posted to stackoverflow since it doesn't directly relate to ReactQL. That tutorial vid is nearly 2.5 years old; it's very likely that the Sequelize API has changed since then.
