### ISSUE TITLE
Remove GraphQL?

### ISSUE THREAD

**Issue by iKonrad** [reactql/cli#110]
Hi, is there any way to get rid of GraphQL without sacrificing SSR and Redux rehydration?

I've tried removing everything from `server_dev` and `entry/server` but I'm stuck at this line, which seems to create a Redux store based on the Apollo client:

```
// Create a new Redux store
const store = createNewStore(client);
```

I've also found your post regarding removing GraphQL https://github.com/reactql/cli/issues/39 so I assume this is doable.
I wonder if you could give me a few pointers on how to remove the GraphQL back-end.

Thanks.

**Comment by chasm** [comment]
I can see removing almost anything else, but it's called "ReactQL" --> React and GraphQL. There are plenty of other options out there. Ripping GraphQL out of ReactQL doesn't seem to me to be worth much effort.

**Comment by leebenson** [comment]
Check out my new Launch.js project (which, incidentally, the next version of ReactQL will be moving to): https://github.com/launchjs/app

There's an example in the readme showing a simple universal React set-up. There's also now a [CSS preset](https://github.com/launchjs/styles), and images/compression will be coming soon.

You could customise that example as needed and wind up with something that's pretty close to what ReactQL already does.

Failing that, there's Create-React-App and similar projects that have a generic React focus.
