### ISSUE TITLE
localStorage, best place to implement ?

### ISSUE THREAD

**Issue by MassivDash** [reactql/cli#112]
Hello, 
I am having a bit trouble of setting up local storage for the redux state. Where is the best place to save state and load the state ? 

thanks.

**Comment by jonoirwinrsa** [comment]
Hey @SpaceGhost - have you tried out redux persist?

**Comment by MassivDash** [comment]
I am trying to save a simple array to local storage, then retrieve it (my list). I managed to save state with subscribe, however it's looks like it's overwritten each time when refresh is hit. 

Is persist really needed for that ? 
I tried to load state persistedState in in the create new store class but cannot get my head around where exactly should I put it.

**Comment by MassivDash** [comment]
Closing my issue, forgot to set my redcuers to take in values from the local storage.
