### ISSUE TITLE
Running SSR server in development

### ISSUE THREAD

**Issue by jtmthf** [reactql/cli#13]
Right now it doesn't seem like there is a way to run the ssr server in development. This would be useful as a common mistake in React dev is having the server and client checksums not match on hydration. Also it just makes it difficult to test changes to the server as well without doing a full rebuild. I'm thinking the way to go about this is to make a base webpack server config, like browser does, and then have have separate server_dev and server_prod extensions. The server_dev would have unnecessary optimizations not enabled for faster rebuilding and have watch mode turned on. Then use nodemon to watch for rebuilds of the `server.js` output. As I've been filing a number of issues already, I wouldn't mind tackling this and #11 in separate PRs bearing your opinions.

**Comment by leebenson** [comment]
This sounds interesting, @jtmthf. Looking forward to seeing what you come up with.

**Comment by leebenson** [comment]
Moving this to https://github.com/reactql/kit/issues/4
