### ISSUE TITLE
babel spread operator problem

### ISSUE THREAD

**Issue by loelsonk** [reactql/cli#15]
Hello, I've a problem with babel transpiling.

```
npm run start // command I use to run
npm -v 4.1.2
node -v v7.5.0
```

Standard ES6 I copied from [reacttraining examples](https://reacttraining.com/react-router/web/example/auth-workflow).

The code: (don't mind this 1===1, it's just for testing)
```
const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route {...rest} render={props => (

    1===1 ? (
        console.log(props);
      ) : (
        <Redirect to={{
          pathname: '/sign-in',
          state: { from: props.location }
        }}/>
      )
  )}/>
)
```
Besides default reactQL .babelrc I tried following setup:
```
{
  "presets": [ "react", "stage-3",
    ["env", {
      "targets": {
        "node": true
      }
    }]
  ]
}
```
Here is error I am receiving:
![Image](https://i.imgur.com/B1zOoUu.png)

Not sure why it is not working. Clearly I am missing something.

**Comment by leebenson** [comment]
@loelsonk - `npm i -g reactql` to 2.0.1, and this should now work.

**Comment by loelsonk** [comment]
Thanks, it is working now!
