### ISSUE TITLE
Server/browser awareness issue

### ISSUE THREAD

**Issue by netbull** [reactql/cli#16]
When I try this
```javascript
async componentDidMount() {
    if (!SERVER) {
      try {
        await screenfull = import('screenfull');
      } catch (e) {
        console.log('Module did not load!');
      }
    }
  }
```

Build fails with error "Invalid left-hand side in assignment expression" and the ESLinit highlights the **await**

If I change it to this:
```javascript
const screenfull = await import('screenfull');
```

I've got **regeneratorRuntime**
The setup is almost fresh, just few react components.

```
npm -v 4.1.2
node -v v7.6.0
```
Any ideas ?

**Comment by leebenson** [comment]
thanks @netbull - that's a mistake in the docs. I'll get that fixed. Your `const screenfull = await import('screenfull');` is the right way to go.

**Comment by netbull** [comment]
@leebenson that way I've got the 
```
ReferenceError: regeneratorRuntime is not defined
```

**Comment by leebenson** [comment]
Ah, I see. Sounds like an issue with the babel polyfill. Will check that today and get it fixed.

**Comment by leebenson** [comment]
This now works as of [2.1.0](https://github.com/reactql/cli/releases/tag/2.1.0).

Upgrade with `npm i -g reactql`.

Sample component to test:

**app.js**
```js
import React from 'react';

export default class Example extends React.Component {
  constructor() {
    super();
    this.state = {};
  }

  async componentWillMount() {
    this.setState({
      name: await new Promise(resolve => {
        setTimeout(() => resolve('ReactQL'), 1000);
      }),
    });
  }

  render() {
    return (
      <h1>{this.state.name || 'none'}</h1>
    );
  }
}
```

The browser entry is polyfilled to work everywhere. On the server, if you're using < 7.6, `async/await` will be transformed into a generator. On >= 7.6, it'll use native async/await.

**Comment by netbull** [comment]
@leebenson thanks!

for browser is ok, but running 
```
npm run build-run
```
throws exception ** Unexpected token import** if I try to use **this.screenfull = await import('screenfull');**

**Comment by leebenson** [comment]
will investigate this further. On the surface, it seems like an issue with import not being treated like a Promise on the server.

**Comment by mnpenner** [comment]
`await` still doesn't seem to be working. Getting

> regeneratorRuntime is not defined

Not sure what version of kit I'm using but I installed it just a couple days ago.

**Comment by leebenson** [comment]
@mnpenner - are you specifically trying to get `await` to work with imports? This issue is showing up in the browser and not on the server, right?

**Comment by mnpenner** [comment]
In the browser, but not with `import()`. Was trying to await [`self.createImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap) specifically, which returns a Promise.

**Comment by leebenson** [comment]
Sounds like an issue with your environment. The project generated by `reactql new` uses `async/await` in multiple places, and runs out-the-box with `npm start` on Node 7.6+.

Which version of ReactQL are you getting with `reactql version`? Did you try creating a new project with `reactql new`? Are you running with `npm start`?

**Comment by mnpenner** [comment]
@leebenson I managed to reproduce it a brand new install. However, the issue may be related to `worker-loader` or when you add webpack plugins via `!` syntax.

```
❯ node --version
v7.10.1
❯ reactql version
4.8.5
```

Kit  v2.8.5.

Create `src/async.js`:

```js
self.addEventListener('message', async ev => {
  let image = await self.createImageBitmap('TEST');
});
```

Drop this in `src/components/main/index.js`. I put this right above `export default ()`:

```js
import Worker from 'worker-loader!../../async';
const worker = new Worker();

worker.postMessage({hello: 'world'});
```

Run `yarn add worker-loader` to add the package.

Fire up the server: `yarn start`.

Gives error:

> `db426b9….worker.js:733` Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by leebenson** [comment]
@mnpenner - according to https://github.com/webpack-contrib/worker-loader/issues/75, it doesn't seem like Webpack 3.x support has landed yet. Not sure if it's related.
