### ISSUE TITLE
default favicon

### ISSUE THREAD

**Issue by jtmthf** [reactql/cli#26]
There's a funny behavior right now when running in prod. When a request for `favicon.ico` hits the Koa server, a full page render is retuned. Easiest way to fix this would be to use something like https://github.com/jantimon/favicons-webpack-plugin with the project logo. Then it also makes it easy for developers to swap out the favicon later to their project's logo.

**Comment by leebenson** [comment]
The webpack plugin is pretty comprehensive. It generates a bunch of icons that can be used for various sites, and works with [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to generate static HTML containing the `<link>` refs.

This might be overkill for the starter kit. If the user wants to create favicons for different purposes, they can easily use [react-helmet](https://github.com/nfl/react-helmet) (included in the kit) and import those images directly in the JS file to run the image through the regular imagemin compilation chain.

Re: the `/favicon.ico` route, I would handle it as follows:

1. Copy files from `./public` to `./dist/public` automatically. There's a stub for it [here](https://github.com/reactql/kit/blob/master/kit/webpack/browser.js#L103-L113) that's currently commented out. This would enable putting 'static' assets like favicon.ico there, and know it'll be copied over automatically. The purpose of `public` is to put stuff in there that doesn't need any optimisation -- third-party JS, pre-optimised images, etc.

2. *Write a Koa route for an empty /favicon.ico*. If files are copied from `public` to `dist/public`, then hits to `/favico.ico` would first check to see if the file exists. If it does, it's served. If not, write a separate route to throw a `204 No Content` response.

3. *Check to ensure 404s are properly handled*. If /favicon.ico is returning a full-page render, then it's likely other non-existent routes are doing the same. Implement a 404 response for routes that don't match anything if that's not already happening.

**Comment by leebenson** [comment]
Moving this to https://github.com/reactql/kit/issues/1

**Comment by leebenson** [comment]
This has been implemented in https://github.com/reactql/kit/commit/3afbe49c1f26d330b370f1f2ee4f723fe4f1496a btw
