### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by RuairiSpain** [reactql/cli#29]
First, great project and good job.  I had a small issue with the dependencies.  Is the CLI supposed to download all the dependencies?

Here's how to repeat my issue:

Here's my steps:
> reactql new
> cd .\reactql-app\
> npm start
...
npm ERR! code ELIFECYCLE
npm ERR! reactql-app@0.1.0 start: `webpack-dev-server --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactql-app@0.1.0 start script 'webpack-dev-server --colors'.
...

then did a npm install and it fixed the issue.
 > npm install

**Comment by leebenson** [comment]
Thanks for reporting, @RuairiSpain.

Yes, the `reactql` tool is supposed to install all NPM packages for you. It does this with `yarn` (if it's installed) or falls back to `npm` if not available (which should theoretically be on all platforms that Node.js was installed on, unless you installed from source/binaries manually.)

Please provide answers to the following:

- What OS are you using?
- What's the output from...
- `reactql version`?
- `npm -v`
- `node -v`

**Comment by RuairiSpain** [comment]
Hi @leebenson , here's more info.   I've got both yarn and npm installed.  It's likely the script used yarn for the packages and I used blindly did what the getting started guide told me.  I used "npm start"  and probably should have done yarn start.


Windows 10
Error was caused by "npm start", see more details at end of post
reactql 2.2.0
npm -v 3.10.9
node -v 7.9.0
yarn 0.21.3



PS C:\....\reactql-app> npm start

> reactql-app@0.1.0 start C:\...\reactql-app
> webpack-dev-server --colors

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ruair\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.9.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! reactql-app@0.1.0 start: `webpack-dev-server --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactql-app@0.1.0 start script 'webpack-dev-server --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactql-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactql-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactql-app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ruair\Documents\GitHub\reactql\reactql-app\npm-debug.log

**Comment by leebenson** [comment]
Thanks for the info @RuairiSpain. It's very strange that Yarn/NPM isn't being invoked after installing- I tested on my local Windows 10 machine with both yarn and NPM installed, and couldn't replicate the issue.

I'll keep this issue open and do more testing. In the meantime, if anyone else is running into problems with Windows, manually doing the `npm install` step seems to fix it.

**Comment by elfedeb** [comment]
Updating to the latest version of my npm and global packages did it for me.

**Comment by leebenson** [comment]
After further testing, I haven't been able to replicate this issue on my local Windows machine, so hopefully it was a one-off. I'll close this for now - but if anyone else runs into the same problem, will investigate further.
