### ISSUE TITLE
webpack.config.babel.js is not DRY, perhaps use cross-env instead?

### ISSUE THREAD

**Issue by mnpenner** [reactql/cli#33]
I tried renaming the "start" script in package.json to "dev" because that's what I typically use in my other projects, but then I hit this error:

> invoke through npm only

I thought it was because I was using `yarn dev` instead of `npm run dev`, but then I looked at the stack trace and saw where it was coming from.

Point is, it's not very nice to have to keep two different files in sync. Could you perhaps update the commands to something like,

```json
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "cross-env WEBPACK_ENV=browser_prod,server webpack --colors",
    "build-browser": "cross-env WEBPACK_ENV=browser_prod webpack --colors",
    "build-server": "cross-env WEBPACK_ENV=server webpack --colors",
    "build-run": "webpack --colors && node dist/server",
    "lint": "eslint .",
    "server": "node dist/server",
    "start": "cross-env WEBPACK_ENV=browser_dev webpack-dev-server --colors"
  },
```

i.e., use [`cross-env`](https://www.npmjs.com/package/cross-env) to set an environment variable, and then check the environment var in webpack.config.js and load up the additional configs? This is basically what I do and it's been working great.

**Comment by leebenson** [comment]
@mnpenner - I like the idea of keeping config in one place (i.e. `package.json`) and controlling build steps through ENV vars. I'll play with that today and report back when bumped.

**Comment by leebenson** [comment]
added in https://github.com/reactql/kit/releases/tag/1.1.2
