### ISSUE TITLE
Best way to handle subscriptions with server side rendering?

### ISSUE THREAD

**Issue by babsonmatt** [reactql/cli#34]
Seems like right now I'll need to wrap each request for subscription with a check to determine if we're on the client or not?  Any help would be greatly appreciated!

Thanks!

**Comment by leebenson** [comment]
@babsonmatt - I'll be writing a guide to using subscriptions in the docs shortly; I know it's a pretty requested feature. This _may_ lead to some kind of helper in the [kit/lib/apollo.js](https://github.com/reactql/kit/blob/master/kit/lib/apollo.js) that overlays a subscription and does the 'environment' checking for you... the kit hasn't been wired up for subscription support yet, so this is all TBD.

Will leave this issue open until it's added and let you know.

**Comment by babsonmatt** [comment]
Thanks a lot @leebenson

**Comment by scf4** [comment]
Is there a reason you can't call `subscribeToMore` in `componentDidMount`? This is the way I've been doing it in a next.js project.

**Comment by babsonmatt** [comment]
@scf4 websockets don't exist on the backend so it blows up

**Comment by scf4** [comment]
@babsonmatt set up your socket client in `browserClient` in `kit/lib/apollo`. 

Take a look at this example: http://dev.apollodata.com/react/subscriptions.html

They call the subscribe function in `componentWillMount`, which runs on the server. Use `componentDidMount` instead. It only runs on the client so it's safe to call it in there.

**Comment by babsonmatt** [comment]
@scf4 ah, forgot about that difference between componentWillMount/componentDidMount - good call.

**Comment by leebenson** [comment]
I'll go ahead and close this ticket since the componentWillMount/componentDidMount pattern is probably enough to get started with.
