### ISSUE TITLE
Enhancement to allow install in current directory?

### ISSUE THREAD

**Issue by zachlendon** [reactql/cli#37]
I'm wondering if you would considerable it permissable/allowable for ReactQL to be able to install in the current directory?  I can see in the code where this isn't presently allowed, and I'd be willing to do a PR if it'd help, but it's an option I'd like and I'd think others might also.   Thoughts?

**Comment by leebenson** [comment]
You can actually install a ReactQL project into the current folder, so long as the dir is empty. Just specify `.` when it asks where you'd like to install.

It will refuse to install if the folder isn't empty, as a sanity check against overwriting existing files.
