### ISSUE TITLE
Demo with Redux

### ISSUE THREAD

**Issue by CaptainChemist** [reactql/cli#39]
I am having a hard time trying to figure how to add redux with graphQL, it would be really amazing if you had some documentation for a sample query just to give us an idea of how to hook up the action creator, connect and reduced. I love this package, thanks for putting it together!

**Comment by leebenson** [comment]
Sure, good idea. I'm tracking that in https://github.com/reactql/docs/issues/9

**Comment by leebenson** [comment]
@CaptainChemist - I put together a demo of a simple to-do list in ReactQL [here](https://github.com/reactql/examples/tree/master/no-graphql).

In this example, I removed GraphQL to show how ReactQL could be used alongside Redux without requiring a GraphQL back-end. However, the same concepts apply - you can just start a new ReactQL project, add another reducer [like I do here](https://github.com/reactql/examples/blob/master/no-graphql/kit/lib/redux.js#L26), and then build components that 'listen' to Redux state (or dispatch actions) like I do [in these lines](https://github.com/reactql/examples/blob/master/no-graphql/src/app.js#L98-L165).

Hope that helps!

**Comment by leebenson** [comment]
@CaptainChemist - I've also finished new docs on [how to add Redux stores here](https://reactql.org/docs/state) - let me know if that helps!
