### ISSUE TITLE
Add CLI option for JS/TS selection

### ISSUE THREAD

**Issue by zachlendon** [reactql/cli#41]
Currently there are the following CLI options:

Options:
  --name, -n     New project name
  --desc, -d     Project description
  --path, -p     Path to install the starter kit
  --license, -l  License for pkg.json
  --help         Show help

It would seem that if there was a Javascript/Typescript option that a user could pass in, that one could do `reactql new <all options>` and avoid the interactivity of the CLI, if their use case so called for it.  Adding this option seems within the confines of the intent of ReactQL - all the other CLI options are there, except for JS/TS.  

Enhancement request for sure in my mind, but would be a nice to have...

**Comment by leebenson** [comment]
Thanks @zachlendon, will definitely add this.
