### ISSUE TITLE
Webpack config improvements

### ISSUE THREAD

**Issue by tanekim77** [reactql/cli#44]
1. Wouldn't it be better if we change  Webpack's config file's 'module.loaders' to 'module.rules' to confirm to Webpack 2's standard?, according to 
https://webpack.js.org/guides/migrating/
Confirming to the recommended standard would give users confidence in that it's being well maintained.

2. Wouldn't it be better if we used Webpack-dev-middleware + Webpack-hot-middleware instead of Webpack-dev-server, because WDM + WHM gives user more flexibility and functionality?

**Comment by leebenson** [comment]
@tanekim77 -

1. Sure, I'll update to `rules` in the next version.

2. I'd be interested to hear what you feel webpack-dev-middleware + webpack-hot-middleware would provide over the current config? I get that it'd open up the config options... but do you have any specific features that you feel are missing?

**Comment by tanekim77** [comment]
The author in the following article shared her experience with the need of webpack-middleware in certain type of project:
https://www.codazen.com/configuring-webpack-middleware/

She said in quote, "I’ve used webpack-dev-server before, and I still love using it. But I was working on configuring isomorphic-relay-router on a little project and was curious about what a hot-loading dev setup would look like with webpack. I needed a finer control than webpack-dev-server offered in this situation, so I delved into webpack middleware."

Using webpack-hot/dev-middlewares may serve broader audience with different project requirements.

**Comment by leebenson** [comment]
I'd be open to a PR, as long as it conforms to the current Webpack config layout. If I don't get any takers, I'll probably tackle this myself in future.

**Comment by leebenson** [comment]
Webpack v2 refactor in [kit v1.9.0](https://github.com/reactql/kit/releases/tag/1.9.0)
