### ISSUE TITLE
ports on heroku 

### ISSUE THREAD

**Issue by lawwantsin** [reactql/cli#45]
Hey, great kit.  Really blows the rest of them out of the water.
I'm attempting to run on heroku.  I've given up trying to get heroku to do a `npm run build` and am just building locally and pushing dist.  

Here's my question.  Heroku sets the port dynamically for web processes through `process.env.PORT`  so i added it in `kit/lib/env.js`

```
const defaultPorts = {
  production: {
    server: process.env.PORT,
  },
  development: {
    browser: 8080,
    server: 8081,
  },
};
```

heroku gives me this error, with the same 4000 port.  nothing changed.  any ideas?
![image](https://user-images.githubusercontent.com/18623/27345880-0d8f0890-55a0-11e7-82fd-b6a85cfc3f43.png)

what am I doing wrong?  thanks in advance.

**Comment by leebenson** [comment]
Thanks for the kind words, @lawwantsin - glad you're liking it!

The issue you're running into is that `kit/lib/env.js` is being used _pre-transpilation_ -- once Webpack has done its thing and dumped out the resulting `dist/server.js`, the source code in `kit/lib/env.js` has already been used, and that file is no longer touched when running the server.

You therefore have two options:

1. Change `kit/lib/env.js` to pull from `process.env.PORT` _before_ you run `npm run build`, so that the environment variable is available at runtime.

or (easier):

2. Run the start-up command `SERVER_PROD_PORT=$PORT npm run server` in Heroku instead, which the ReactQL web server will use to override the default port 4000. This is better because then you don't need to mess with the kit internals.

Any other Qs, just let me know.

**Comment by YoniH** [comment]
@leebenson How exactly would that start-up command implemented in heroku?

I added a script to package.json:
```
"heroku-server": "cross-env SERVER_PROD_PORT=$PORT SERVER_PROD_HOST=0.0.0.0 npm run server"
```

And I added a Procfile:
```
web: npm run build && npm run heroku-server
```

Still I'm getting this error:

2017-10-09T00:07:16.098923+00:00 heroku[web.1]: Starting process with command `npm run build && npm run heroku-server`
2017-10-09T00:07:21.281187+00:00 app[web.1]: 
2017-10-09T00:07:21.281201+00:00 app[web.1]: > myproject@1.16.0 build /app
2017-10-09T00:07:21.281202+00:00 app[web.1]: > cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors
2017-10-09T00:07:21.281203+00:00 app[web.1]: 
2017-10-09T00:08:03.972462+00:00 app[web.1]: (node:25) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
2017-10-09T00:08:16.719710+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2017-10-09T00:08:16.719710+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-10-09T00:08:17.039527+00:00 heroku[web.1]: Process exited with status 137
2017-10-09T00:08:17.055198+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by YoniH** [comment]
Anyone? @leebenson?

**Comment by barbarNik** [comment]
Guys i have a similar issue with heroku and looks like SERVER_PROD_PORT has no effect at all

**Comment by Kamill90** [comment]
Hi. I try to deploy my app on Heroku. However, when I build my project, in dist folder, there is neither package file nor node_module folder. Should I copy package.json and node_module folder to dist? Or push to heroku whole app? I can't get a concept. 
Thanks.

**Comment by YoniH** [comment]
@Kamill90 Don't worry about your local dist folder. One way to deploy your app to Heroku is to push your code to Heroku through git. Heroku will build and deploy it. Here's how to set things up: https://devcenter.heroku.com/articles/getting-started-with-nodejs#deploy-the-app

**Comment by Kamill90** [comment]
Thank you, that makes things simpler... 
I added to script and Procfile same commands as you suggested. After pushing it to heroku I get no error in logs, but following heroku-app link, i see only "Application error
An error occurred in the application and your page could not be served..."

**Comment by YoniH** [comment]
Check the logs on heroku then, that will give you a clue. This is not necessarily related to the ports issue

**Comment by Kamill90** [comment]
@YoniH Yes, thanks. Indeed it is offtopic. I continue looking for solution in here https://stackoverflow.com/questions/48531545/heroku-failed-at-the-build-script-but-heroku-local-web-is-fine

**Comment by Kamill90** [comment]
Ok, I got to the point where my problem is: to make host: "default", especially that Heroku doesn't take process.env.HOST or localhost. 
How should I configure my env.js or script for that? 
@leebenson  @YoniH  anyone may share a working example?

**Comment by YoniH** [comment]
In Heroku I defined a config var called HOST with value 0.0.0.0

Here are the relevant parts of my configuration:

procfile:
`web: npm run server`

package.json scripts:
```
    "browser": "cross-env NODE_ENV=development WEBPACK_CONFIG=browser_dev webpack-dev-server --open",
    "build": "cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors",
    "build-analyze": "cross-env BUNDLE_ANALYZER=1 NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors",
    "build-browser": "cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod webpack --colors",
    "build-run": "npm run build && npm run server",
    "build-static": "cross-env NODE_ENV=production WEBPACK_CONFIG=static webpack --colors",
    "build-static-run": "npm run build-static && npm run static",
    "clean": "rimraf dist",
    "postinstall": "npm run build",
    "lint": "eslint .",
    "server": "node dist/server",
    "server-dev": "cross-env NODE_ENV=development WEBPACK_CONFIG=server_dev webpack --colors",
    "start": "run-p browser server-dev",
    "static": "serve -s dist/public",
    "test": "jest"

```
In server_dev.js:
```
      new webpack.DefinePlugin({
        // We ARE running on the server
        SERVER: true,
        'process.env.HOST': JSON.stringify(process.env.HOST || 'localhost'),
        'process.env.SSL_PORT': process.env.SSL_PORT ? JSON.stringify(process.env.SSL_PORT) : null,
        'process.env.NODE_ENV': JSON.stringify('development'),
        'process.env.DEBUG': true,
      }),
```

In server_prod.js:
```
    new webpack.DefinePlugin({
      // We ARE running on the server
      SERVER: true,
      'process.env.HOST': JSON.stringify(process.env.HOST || 'localhost'),
      'process.env.SSL_PORT': process.env.SSL_PORT ? JSON.stringify(process.env.SSL_PORT) : null,
      'process.env.NODE_ENV': JSON.stringify('production'),
      'process.env.DEBUG': false,
    }),
```

In env.js:
```
const getServerHost = () => process.env.HOST;
export const getServerPort = () => process.env.PORT || (process.env.NODE_ENV === 'production' ? 4000 : 8081);

// Get the protocol://host:port of where the current server would bind
export function getServerURL(host = getServerHost(), port = getServerPort(), allowSSL = true) {
  // Check for SSL
  if (allowSSL && process.env.SSL_PORT) {
    const stub = `https://${host || process.env.HOST}`;

    // If we're on port 443, that's 'regular' SSL so no need to specify port
    if (process.env.SSL_PORT === '443') return stub;
    return `${stub}:${process.env.SSL_PORT}`;
  }

  // Plain HTTP
  const stub = `http://${host || process.env.HOST}`;

  // If we're on port 80, that's 'regular' HTTP so no need to specify port
  if (port === '80') return stub;
  return `${stub}:${port}`;
}
```

In entry/server.js:
```
  if (config.enableHTTP) {
    servers.push(
      http.createServer(app.callback()).listen(getServerPort()),
    );
  }
```

**Comment by jppgks** [comment]
FYI, I used Heroku's container registry and runtime to deploy, no port config needed:

1. If you haven't already done so, create new Heroku app:
```shell
heroku create YOUR_APP_NAME
```
2. Build Docker image:
```shell
docker build -t registry.heroku.com/YOUR_APP_NAME/web .
```
3. Push Docker image to Heroku registry:
```shell
docker push registry.heroku.com/YOUR_APP_NAME/web
```
4. Release the pushed image to the web process:
```shell
heroku container:release web -a YOUR_APP_NAME
```
