### ISSUE TITLE
Community Platforms

### ISSUE THREAD

**Issue by valamorgon** [reactql/cli#46]
We do need a gitter and forum for community needs. Also I'd like to see a twitter account for recent updates. It seems like finally we have a full stack graphql and developer interface, let's power up the community.

**Comment by leebenson** [comment]
https://twitter.com/reactql <-- not much, but it's a start!

**Comment by leebenson** [comment]
https://gitter.im/reactql/Lobby <-- for ReactQL chat

**Comment by leebenson** [comment]
Please follow https://twitter.com/reactql and let's start building this thing up!
