### ISSUE TITLE
debugging/inspecting in SSR server_dev.js

### ISSUE THREAD

**Issue by lawwantsin** [reactql/cli#48]
Hey Lee,
I'm looking to debug the `server_dev.js` process in the [node-inspector](https://nodejs.org/en/docs/guides/debugging-getting-started).   In `server_dev.js`, the childProcess.fork seems the place to put a debug signal.  but it doesn't work.  Have you managed to debug a node process that webpack keeps killing and re-spawning?

```js
class ServerDevPlugin {
  apply(compiler) {
    compiler.plugin('done', () => {
      if (this.server) this.server.kill();
      this.server = childProcess.fork(path.resolve(PATHS.dist, 'server_dev.js'), {
        cwd: PATHS.dist,
      });
      this.server.send('SIGUSR1')
    });
  }
}
````

**Comment by crazyfrozenpenguin** [comment]
@lawwantsin, have you been able to figure out how to debug server side?

**Comment by leebenson** [comment]
Apologies for not responding sooner. I'll get some time in soon to investigate. Happy to accept PRs in the meantime.

**Comment by lawwantsin** [comment]
i gave up on ReactQL (and all boilerplates) for this reason.  Chrome debugging works great when running the server via nodemon on node 8.  Pushing server code through webpack seems unnecessarily complex and I'm not sure of the benefit.

**Comment by leebenson** [comment]
<img width="1116" alt="screen shot 2017-07-30 at 20 47 45" src="https://user-images.githubusercontent.com/719722/28756538-71f06102-7568-11e7-8aac-fcc77319d71b.png">

----

```js
class ServerDevPlugin {
  apply(compiler) {
    compiler.plugin('done', () => {
      if (this.server) this.server.kill();
      this.server = childProcess.fork(path.resolve(PATHS.dist, 'server_dev.js'), {
        cwd: PATHS.dist,
        silent: false,
        execArgv: ['--inspect'],
      });
    });
  }
}
```

**Comment by leebenson** [comment]
@lawwantsin - the point of Webpack on the server is not having to make special provisions for your code; it's implicitly isomorphic.

You can write `import someImage from 'src/image.png` or `import css from './someSassFile.scss` and know that it'll work perfectly everywhere -- without worrying about server-side file hashing, Zopfli/Brotli compression, considering how CSS classes might match up, etc.

In fact, it's the reason you can `import` anything at all.

Taking Webpack out of the equation on the server pushes those considerations into userland - and they're generally not easy problems to solve.

Of course, you don't need to use Webpack. You could write your code using `require()`, avoid importing files relative to the project root, avoid treating images or CSS like local JS code, and handle your own build process via gulpfiles or similar.

But the aim of ReactQL is to avoid complexity, and keep the browser and server (for the most part!) singing from the same sheet without worrying about that stuff.

**Comment by leebenson** [comment]
`--inspect` switch released in https://github.com/reactql/kit/releases/tag/1.17.0

Added to CLI https://github.com/reactql/cli/releases/tag/3.9.0

Upgrade with `npm i -g reactql`
