### ISSUE TITLE
Unable to choose between ES6 and Typescript during "reactgl new" setup

### ISSUE THREAD

**Issue by sunweiyang** [reactql/cli#50]
First of all, fantastic repo, documentation, and onboarding videos. One of the most complete and polished experiences I've ever had with a boilerplate -- thank you so much!

I have successfully installed via `npm install -g reactql`. However, I never encountered the opportunity to choose between ES6 and Typescript ("Which version of the kit would you like?") that was supposed to appear right after "Where to install?".

Here is my terminal output:

```
$ reactql new
================================================================================

██████╗ ███████╗ █████╗  ██████╗████████╗ ██████╗ ██╗
██╔══██╗██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔═══██╗██║
██████╔╝█████╗  ███████║██║        ██║   ██║   ██║██║   v3.7.1
██╔══██╗██╔══╝  ██╔══██║██║        ██║   ██║▄▄ ██║██║
██║  ██║███████╗██║  ██║╚██████╗   ██║   ╚██████╔╝███████╗

Spawning new project...

? Project name? test
? Project description? New ReactQL project
? License? UNLICENSED
? Where to install? /Users/sunw/test

================================================================================

Downloading kit v1.15.1 from Github...
```

**Comment by leebenson** [comment]
My pleasure @sunweiyang, glad you're liking it!

Typescript support has temporarily been removed from the CLI, pending https://github.com/reactql/kit.ts/issues/18

I'll enable it as soon as the TS version is brought up to date. It's maintained by a community member, so I can't offer an ETA for it, unfortunately. My advice would be to stick with the Javascript version for now.
