### ISSUE TITLE
browser run not working

### ISSUE THREAD

**Issue by arif-hanif** [reactql/cli#54]
i have an issue with latest build with browser hot reloading not loading website at all with clean install with CLI, SSR is working.

**Comment by leebenson** [comment]
Could you let me know a little more about your environment, and steps to reproduce please?

`npm start` is working for me locally on both http://localhost:8080 (browser hot-code reload) and http://localhost:8081 (SSR) with a new install on kit 1.16.0 via CLI 3.8.0

**Comment by arif-hanif** [comment]
i cleaned my install of node and npm and everything works fine now
