### ISSUE TITLE
SVG not loaded correctly in server_dev

### ISSUE THREAD

**Issue by bensventures** [reactql/cli#57]
Hi, first of all thanks the great starter kit, after trying many, ReactQL proved to be the most straight forward and fully featured I was looking for.

I am running into an issue while importing svg files in a react component. 

```
import enFlag from 'flag-svg-collection/flags/4x3/gb.svg';
```

The browser bundle is done correctly and the svg loads fine but when I refresh the page the server tries to render the components and fails trying to load the svg with this error:

```
/path-to/node_modules/flag-svg-collection/flags/4x3/gb.svg:1
(function (exports, require, module, __filename, __dirname) { <svg xmlns="http://www.w3.org/2000/svg" height="480" width="640" viewBox="0 0 640 480">
                                                              ^

SyntaxError: Unexpected token <
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.defineProperty.value (/path-to/dist/server_dev.js:1694:18)
```
My guess is that the svg is not being run through the file-loader but I've been checking the webpack configs and everything looks fine. Any ideas / pointers?

**Comment by leebenson** [comment]
Thanks for submitting the issue. Looks like this is limited to the web server; the hot-reloaded browser handles the SVG type correctly. I'll investigate.

**Comment by leebenson** [comment]
Okay, I see what's up. The current server config treats _all_ `node_modules` imports as external, so images are not hashed, minified and copied into the resulting `dist/public/asset` folder when pulled from an NPM package -- only your local source.

I'll push a new release that treats images/fonts pulled from NPM properly.

Should have it done tonight. Will report back here.

**Comment by leebenson** [comment]
Fixed in [kit v1.17.1](https://github.com/reactql/kit/releases/tag/1.17.1), available via [CLI v3.9.1](https://github.com/reactql/cli/releases/tag/3.9.1).

Run `npm -g reactql` to upgrade your CLI version.

Demo:

<img width="704" alt="screen shot 2017-08-02 at 20 19 33" src="https://user-images.githubusercontent.com/719722/28891130-516221e0-77c1-11e7-9e70-e06660fe3649.png">

**Comment by bensventures** [comment]
Working great, thanks for the quick solution.

**Comment by leebenson** [comment]
No prob @bensventures
