### ISSUE TITLE
[v4.1.0] webpack "failed to compile" when using sequelize

### ISSUE THREAD

**Issue by treefort** [reactql/cli#59]
OS: macOS 10.12.2
Node: v7.6.0
Npm: 4.1.2

Steps:
1. `reactql new` (created new project using defaults)
2. `npm install sequelize --save` (fine)
3. added `import Sequelize from 'sequelize';` to /src/app.js
4. `npm start`

Getting this error:
```
Failed to compile.

(undefined) ./node_modules/sequelize/lib/dialects/mssql/query.js
Module not found: Error: Can't resolve 'tedious' in '/Users/{my username}/Documents/reactql/reactql-app/node_modules/sequelize/lib/dialects/mssql'
 @ ./node_modules/sequelize/lib/dialects/mssql/query.js 10:14-32
 @ ./node_modules/sequelize/lib/dialects/mssql/index.js
 @ ./node_modules/sequelize/lib/sequelize.js
 @ ./node_modules/sequelize/index.js
 @ ./src/app.js
 @ ./kit/entry/browser.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./kit/entry/browser.js
```

I got the same result on a windows 10 machine. Since I'm not seeing any related issues in the sequelize repo, I'm assuming this has something to do with the webpack config, perhaps?

**Comment by soundcontrolben** [comment]
I had a similar issue. This resolved it.
https://github.com/liady/webpack-node-externals

**Comment by treefort** [comment]
awesome—I'll take a look. thank you, Ben!

**Comment by leebenson** [comment]
Note that we're actually already using `webpack-node-externals` - see https://github.com/reactql/kit/blob/master/kit/webpack/server.js#L102-L108

So you can add code there if you need to 'whitelist' other mods.

**Comment by leebenson** [comment]
I'll close this for now; feel free to re-open if `webpack-node-externals` doesn't solve it

**Comment by treefort** [comment]
excellent—thanks! I figured there were at least a few different ways to work around this, but it's always nice to get the _optimal_ solution from people with intimate knowledge of the framework.

**Comment by treefort** [comment]
@leebenson https://github.com/reactql/kit/blob/master/kit/webpack/server.js#L102-L108

if I'm reading this correctly, it appears as though all modules in the `node_modules` directory should already be excluded in the bundle with the exception of fonts and images. is that accurate?

**Comment by leebenson** [comment]
correct @treefort, that's what it's supposed to be doing.  I'll be using Sequelize shortly re: adding authentication, so will let you know if I encounter the same thing

**Comment by treefort** [comment]
much appreciated, @leebenson—and thanks for ReactQL :)
