### ISSUE TITLE
express.js

### ISSUE THREAD

**Issue by ablbol** [reactql/cli#60]
Thanks for this starter kit.
I am not familiar with Koa server and I was wondering if you have this kit with express.js instead?  I have existing code that runs on express.js and I don't know Koa.  How hard is it to change the kit to express? If any body has done it, please let me know.
Thanks

**Comment by leebenson** [comment]
You could edit `kit/entry/server.js` and re-write it with _Express_ if you wanted, but I wouldn't recommend it.

Koa uses Promises as route handlers, which makes it possible to have middleware that 'awaits' further handlers, and thus interact with different parts of the request. We use that in the 'timer' as shown here:

```js
  // It's useful to see how long a request takes to respond.  Add the
  // timing to a HTTP Response header
  .use(async (ctx, next) => {
    const start = ms.now();
    await next(); // <--- this 'yields' to the next handler, and resumes when it's done!
    const end = ms.parse(ms.since(start));
    const total = end.microseconds + (end.milliseconds * 1e3) + (end.seconds * 1e6);
    ctx.set('Response-Time', `${total / 1e3}ms`);
  });
```

AFAIK, you can't use that pattern in express, which makes it harder for a kit like ReactQL to implement convenience handlers like the one above.

I'd recommend you spend a few mins on http://koajs.com/ - it's basically 90% express, but using async functions as route handlers and the route 'context' being passed as an explicit parameter. It's the same Node HTTP server under the hood.

**Comment by ablbol** [comment]
Good point. Thanks for letting me know.
Does Graphql support subscriptions with Koa? I really need it for my current project.

**Comment by leebenson** [comment]
Yes, check out http://dev.apollodata.com/tools/graphql-subscriptions/

It hasn't been implemented in the ReactQL kit, but might be something that's added later.
