### ISSUE TITLE
Hot module Replacement not working in new Project

### ISSUE THREAD

**Issue by Ahakke** [reactql/cli#62]
Hello,

unfortunately, the HMR does not refresh any file in the starter project. When I start the project the cli shows everything like it should. The console of chrome shows that HMR is enabled. But when I save a file only the server side rendering of the cli refreshes but nothing else. 

Do you have an idea? 

Thanks in advance

**Comment by leebenson** [comment]
Are you using localhost:8080 (i.e. the browser-rendered version)? Which files are you attempting to change? What's your environment (Windows, Mac, Linux, etc)?

**Comment by Ahakke** [comment]
Ubuntu 16.04
node >8
browser version

i want to change usual components like the entry one:
names of the route or changing the color css or any other change in etc..

The browser reacts to savings within the entry folder, lib folder but no other..

**Comment by Ahakke** [comment]
It seems to be, that my operating system was messing around. I have clean installed Ubuntu and now it is working lika a charm...

Thanks for this awesome Project
Cheers

**Comment by leebenson** [comment]
np @Ahakke, glad you got it working.
