### ISSUE TITLE
peer dependency warnings?

### ISSUE THREAD

**Issue by brambow** [reactql/cli#70]
Just getting started with ReactQL - looks great!

Do I need to be worried about any of these peer dependency warnings?  Seems like all these packages do exist in the reactql project, just possibly at versions more recent than what these modules use as peer dependencies.

![image](https://user-images.githubusercontent.com/6227786/30114156-fee7833a-92e4-11e7-8d14-0468873127e7.png)

**Comment by leebenson** [comment]
nah, ignore them - just a few third-party NPMs lagging behind. They'll update in due course. In the meantime, everything should still work as before... feel free to re-open if you run into any issues.
