### ISSUE TITLE
Configure a custom history for use outside of the the components.

### ISSUE THREAD

**Issue by delmendo** [reactql/cli#72]
I'm working thru Auth0 integration and their library examples use the history module outside of the component system. (That allow the authentication process to manage some history changes.) I followed the guidance from - https://github.com/ReactTraining/react-router/blob/master/FAQ.md#how-do-i-access-the-history-object-outside-of-components  But it required me to modify the kit.  I wondered if there was a better way to do that or if you might consider it.

**Comment by leebenson** [comment]
I think this is possibly related to https://github.com/reactql/kit/issues/68 - I'll close this and track there.
