### ISSUE TITLE
Can't install any packages 

### ISSUE THREAD

**Issue by anand-a6** [reactql/cli#73]
This shows when I try to install any packages to my project 

![error1](https://user-images.githubusercontent.com/15985328/30380213-0d6d3cc2-98aa-11e7-9564-bcefae4a819a.PNG)

![error2](https://user-images.githubusercontent.com/15985328/30380220-13a3845c-98aa-11e7-8fb2-4b4be586f215.PNG)

**Comment by leebenson** [comment]
Install Python 2.7 or above, then `npm rebuild node-zopfli`. Also make sure you have a C compiler installed locally -> https://github.com/pierreinglebert/node-zopfli#prerequisites-for-building
