### ISSUE TITLE
Development mode server only listens on loopback interface

### ISSUE THREAD

**Issue by treefort** [reactql/cli#74]
I'd like to test my app on various devices on my network, to no avail (`connection refused`). 

Running `npm start` yields:
![image](https://user-images.githubusercontent.com/1132492/30524173-a450d698-9bbc-11e7-8082-2806db762b53.png)

However, I see that node is only listening on the loopback interface.
![image](https://user-images.githubusercontent.com/1132492/30524193-f170a818-9bbc-11e7-9d52-8bbf90ea3b44.png)

I've tested this on win10 and macOS machines with identical results.

**Comment by leebenson** [comment]
Try this:
`HOST=0.0.0.0 npm start`

**Comment by treefort** [comment]
I set `HOST` to 0.0.0.0 but that didn't appear to change anything.
