### ISSUE TITLE
async function error

### ISSUE THREAD

**Issue by FinnFrotscher** [reactql/cli#82]
The terminal displays this error when starting a fresh cli install.

```
/Users/Finn/Code/bjj/bjj-training-planner/node_modules/koa-send/index.js:37
async function send (ctx, path, opts = {}) {
```

and even tho  `"plugins": ["syntax-async-functions"]` is installed in `.babelrc`, babel throws another error on  functions using `async`

```
Using babel-core at
/Users/Finn/Code/bjj/bjj-training-planner/node_modules/babel-core/index.js
 
  30 |   }
  31 | 
> 32 |   _createLink = async () => {
     |               ^
  33 |     console.log(this.state)
  34 |   }
  35 | }
```

**Comment by leebenson** [comment]
which version of Node are you using?

**Comment by FinnFrotscher** [comment]
now that you asked i upgraded to `node v8.9`  and its working. i also removed `"syntax-async-functions"`. thank you.
are you still actively developing this tool?

**Comment by leebenson** [comment]
np.

Yup, I'm actively developing ReactQL and using it in several production projects. The [kit](https://github.com/reactql/kit) is where most of the action is.

**Comment by FinnFrotscher** [comment]
are you familiar with Meteor?

**Comment by leebenson** [comment]
yes, I was an early Meteor fan/user. Apollo, the GraphQL engine that ReactQL uses, is made by the Meteor team.
