### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by blntylmn** [reactql/cli#87]
Hi again. I'm trying to integrate some jquery modules. So I'm trying to implement "Environment awareness" part of the document for importing some module only client side. On "hot-reloading browser in development mode" everthing is fine but  the "server-side rendering in development mode" crashing by "SyntaxError: Unexpected token import" error with output of console something like below:
```
.........dist/server_dev.js:1486
const init = await import('../helpers/functions/init');
                   ^^^^^^
```

**Comment by blntylmn** [comment]
Ok I tried it with require and build error is gone. But I have another problem now. I'm using [root]/kit/views/browser.html and webpack.html for including third party .css and .js files but somehow they are not included "server-side rendering in development mode".. Where should I include them ?
Especialy I am trying to find the correct way using "JQuery" with ReactQL :)

**Comment by leebenson** [comment]
ReactQL is bundled with [react-helmet](https://github.com/nfl/react-helmet), which allows you to set header content like:

```
<Helmet>
  <script src="link/to/external/script.js" />
  <link href="link/to/external.css" />
</Helmet>
```

Note: This will be loaded asynchronously. If you want sync loading, you will need to hard-code in both `kit/views/browser.html` and `kit/views/ssr.js`

**Comment by blntylmn** [comment]
Hardoced them both kit/views/browser.html and kit/views/ssr.js solved the problem and now everything work as expected.. Maybe it can be a good idea to add a section like 'integrating third party css and js files" in document. (or at least link this issue on main README). Because this was the hardest part in every starter kit I tried before. And none of them had documentation about this.

**Comment by blntylmn** [comment]
Btw the dynamic import thing still crashes on "server side rendering". Currently I am using require instead.

**Comment by leebenson** [comment]
> Maybe it can be a good idea to add a section like 'integrating third party css and js files" in document. (or at least link this issue on main README)

Pretty much all of the documentation will need re-writing with kit v3, so this is a to-do for later.

**Comment by leebenson** [comment]
> Btw the dynamic import thing still crashes on "server side rendering". Currently I am using require instead.

Please share a full code sample and I'll take a look. Dynamic imports should be working.

**Comment by leebenson** [comment]
Here's a minimal example of working dynamic imports:

**src/test.js**
```js
export default 'File imported successfully!';
```

**src/app.js**
```js
import React from 'react';
import config from 'kit/config';

config.enableGraphQLServer();

export default class Main extends React.PureComponent {
  state = {}
  getImport = async () => {
    this.setState({
      imported: (await import('src/test')).default,
    });
  }
  render() {
    return (
      <div>
        <h1>Dynamic import example</h1>
        <button onClick={this.getImport}>Click to import</button>
        <p>
          Returned from import: {this.state.imported}
        </p>
      </div>
    );
  }
}
```

Result:

<img width="946" alt="screen shot 2017-11-30 at 15 41 30" src="https://user-images.githubusercontent.com/719722/33439360-29d105f6-d5e5-11e7-9166-a9175a363bac.png">
