### ISSUE TITLE
Production build browser bundle is still pointing at localhost when run on a remote server. 

### ISSUE THREAD

**Issue by birdiesanders** [reactql/cli#89]
I have enabled the flag in the config file, yet it still is pointing at localhost for gql queries. Is there somewhere else that I need to be looking at? I have gone through the docs you have, but nothing there seems to be of much help.

**Comment by DanielRSnell** [comment]
Same issue for myself, i'll let you know if I find a solution!

**Comment by leebenson** [comment]
In your `src/app.js` file, you can use `config.setGraphQLEndpoint()` to specify the exact URL where your GraphQL server is running in production.

This is an universal function that will work on both the server and client, so just stick it in `src/app.js` and you're good to go. e.g.:

```js
config.setGraphQLEndpoint('https://example.com/path/to/graphql');
```
