### ISSUE TITLE
CSS does not load when using Docker Container

### ISSUE THREAD

**Issue by MaximilianKindshofer** [reactql/cli#97]
I build the docker container and published it with Rancher on my webserver

The CSS and the SVG do not load corretly:

Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://domainname/assets/css/style.c57177aeb7afdf15b74a16a44dbaada3.css".

In kit/views/ssr.js I in Line 22 I added type="text/css" to the Link element. This solved the problem.

**Comment by SaranyaaVR** [comment]
How was this solved?  The extrenal css for loading page symbol works locally but not when I run dash in a docker container.

**Comment by leebenson** [comment]
@SaranyaaVR, before I dig into this, are you using the new kit or the old one?
